-- Create a table for public profiles
create table profiles (
  id int generated by default as identity primary key,
  uid uuid references auth.users on delete cascade not null,
  full_name text not null,
  pronouns text,
  about_me text,
  avatar_url text not null,
  updated_at timestamp with time zone not null,
  karma int default 1000,
  helped int default 0,

  constraint full_name_length check (char_length(full_name) > 0)
);
-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

-- remove edit access to karma and helped
revoke update on profiles from public;
grant update(full_name, pronouns, about_me, avatar_url, updated_at) on profiles to public;

create policy "Users can update own profile except karma and helped." on profiles
  for update using (auth.uid() = uid);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
-- See https://supabase.com/docs/guides/auth/managing-user-data#using-triggers for more details.

--Add existing rows from auth.users
do
$$
declare
  row record;
begin
  for row in select id, created_at, raw_user_meta_data
    from auth.users 
    order by raw_user_meta_data->>'full_name'
  loop 
    insert into public.profiles (uid, updated_at, full_name, avatar_url)
    values (row.id, row.created_at, row.raw_user_meta_data->>'full_name', 'TODO: add default avatar url');
  end loop;
end;
$$;

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (uid, updated_at, full_name, avatar_url)
  values (new.id,
          new.created_at,
          new.raw_user_meta_data->>'full_name',
          'TODO: add default avatar url');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
